apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inveniordm
  namespace: argocd
spec:
  project: invenio-project
  source:
    repoURL: https://inveniosoftware.github.io/helm-invenio/
    chart: invenio
    targetRevision: "0.8.1"
    helm:
      values: |
        host: inveniordm.cyverse.at
        
        invenio:
          hostname: inveniordm.cyverse.at
          init: true
          demo_data: false
          default_users:
            "admin@inveniordm.cyverse.at": "1234567"
            "user01@inveniordm.cyverse.at": "7891011"
            "user02@inveniordm.cyverse.at": "121314"
          extraConfig:
            SECURITY_REGISTERABLE: "false"
        
        postgresql:
          enabled: true
          auth:
            username: "invenio"
            password: "invenio123"
            database: "invenio"
        
        opensearch:
          enabled: true
        
        redis:
          enabled: true
        
        rabbitmq:
          enabled: true
          auth:
            username: "guest"
            password: "guest123"
            existingPasswordSecret: ""
            existingSecretPasswordKey: "rabbitmq-password"
        
        persistence:
          enabled: true
          access_mode: ReadWriteOnce
        
        web:
          replicas: 1
          startupProbe:
            timeoutSeconds: 30
            failureThreshold: 10
        
        worker:
          replicas: 1
        
        opensearch:
          enabled: true
          master:
            replicas: 1
          data:
            replicas: 1
          coordinating:
            replicas: 1
          ingest:
            replicas: 1
        
        redis:
          enabled: true
          replica:
            replicaCount: 1
  
  destination:
    server: https://kubernetes.default.svc
    namespace: invenio
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true