# External Secrets for InvenioRDM from Vault
---
# PostgreSQL Secret from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-vault-secret
  namespace: invenio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgresql-vault-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: inveniordm/database
        property: postgres_password
    - secretKey: password
      remoteRef:
        key: inveniordm/database
        property: user_password

---
# RabbitMQ Secret from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-vault-secret
  namespace: invenio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: rabbitmq-vault-secret
    creationPolicy: Owner
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: inveniordm/messaging
        property: rabbitmq_password

---
# Invenio User Secrets from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invenio-users-vault-secret
  namespace: invenio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: invenio-users-vault-secret
    creationPolicy: Owner
  data:
    - secretKey: admin_password
      remoteRef:
        key: inveniordm/users
        property: admin_password
    - secretKey: user01_password
      remoteRef:
        key: inveniordm/users
        property: user01_password
    - secretKey: user02_password
      remoteRef:
        key: inveniordm/users
        property: user02_password
